# Generated by Django 6.0.5 on 2026-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('course', models.CharField()),
                ('city', models.CharField()),
            ],
        ),
    ]
